### ISSUE TITLE
New rotation fails with TypeError: cleanText.matchAll

### ISSUE THREAD

**Issue by pilosus** [kmaida/rota-slackbot#37] opened 2021-02-23 07:29 UTC
I've been following README's guide to set up `rota` locally with `ngrok`.
My rota app is installed. I can easily do things like `@rota help` and the bot responds.
But I cannot create a new rotation with something like:
```
@rota new "test" description
```

I get an error:

```
:cry: I'm sorry, I couldn't do that because an error occurred:
TypeError: cleanText.matchAll(...) is not a function or its return value is not iterable
```

In `node.js` output I see the following:

```
TypeError: cleanText.matchAll(...) is not a function or its return value is not iterable
    at Object.parseCmd (/Users/vitaly/git/rota-slackbot/utils/utils.js:108:31)
    at module.exports (/Users/vitaly/git/rota-slackbot/app-mentions/new.js:8:30)
    at app.event (/Users/vitaly/git/rota-slackbot/app-mentions.js:63:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This is how a `POST /slack/events` request looks like according to `ngrok`:

```
{
    "token": "...",
    "team_id": "...",
    "api_app_id": "...",
    "event": {
        "client_msg_id": "...",
        "type": "app_mention",
        "text": "<@U01P006CVDY> new \"test\" desc",
        "user": "...",
        "ts": "1614064660.015100",
        "team": "...",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "zce",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "user",
                                "user_id": "U01P006CVDY"
                            },
                            {
                                "type": "text",
                                "text": " new \"test\" desc"
                            }
                        ]
                    }
                ]
            }
        ],
        "channel": "...",
        "event_ts": "1614064660.015100"
    },
    "type": "event_callback",
    "event_id": "Ev01P6AQKGLC",
    "event_time": 1614064660,
    "authorizations": [
        {
            "enterprise_id": null,
            "team_id": "...",
            "user_id": "...",
            "is_bot": true,
            "is_enterprise_install": false
        }
    ],
    "is_ext_shared_channel": false,
    "event_context": "1-app_mention-T1KGQ5533-C1KGA6UTY"
}
```

My local `node.js` is this one:

```
$ node -v
v10.23.3
```

I've tried with both smart quotes and normal quotes. It's all the same.
To me `"text": "<@U01P006CVDY> new \"test\" desc"` looks just fine, regexp should work. But it doesn't.

What I am doing wrong?

**Comment by kmaida** [comment] 2021-03-18 20:24
I don't see anything wrong with your implementation, and I tried to replicate your issue on two different installs of Rota, but I could not reproduce the error (both apps successfully created new rotations). I did update the repo today to use the latest version of the Bolt library. Please try pulling latest and running `npm install` again to update all the dependencies; I'm not sure if this will fix your issue, but as I'm not able to reproduce it, I would need more information from the `cleanText` function's output. You could try putting a breakpoint or log in the function (it is located [here](https://github.com/kmaida/rota-slackbot/blob/master/utils/utils.js#L57)) in order to identify what it's outputting that is not iterable.

**Comment by kmaida** [comment] 2021-03-19 12:38
Closing issue, as unable to repro. Can reopen or file new issue if problem persists or becomes replicable after pulling latest updates.

**Closed as completed by kmaida** 2021-03-19 12:38 UTC
